alter table WORKSHOP_ORDER_INPUT_OBJECT add constraint FK_WORKSHOP_ORDER_INPUT_OBJECT_PART3 foreign key (PART3_ID) references WORKSHOP_SPARE_PART(ID);
create index IDX_WORKSHOP_ORDER_INPUT_OBJECT_PART3 on WORKSHOP_ORDER_INPUT_OBJECT (PART3_ID);
