alter table WORKSHOP_ORDER_INPUT_OBJECT add constraint FK_WORKSHOP_ORDER_INPUT_OBJECT_PART1 foreign key (PART1_ID) references WORKSHOP_SPARE_PART(ID);
create index IDX_WORKSHOP_ORDER_INPUT_OBJECT_PART1 on WORKSHOP_ORDER_INPUT_OBJECT (PART1_ID);
